version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node index.js
    container_name: app
    hostname: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s docker-entrypoint.sh
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    hostname: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - app
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
